    # Stage 1: Build the Nextjs application
    FROM node:18-alpine AS builder
    WORKDIR /myapp
    COPY package.*  ./
    RUN npm install
    COPY . .
    CMD ["npm", "run", "build"]

    # Stage 2: Create the production image
    FROM node:18-alpine AS runner
    WORKDIR /myapp
    ENV NODE_ENV production
    COPY --from=builder /myapp/.next ./.next
    COPY --from=builder /myapp/node_modules ./node_modules
    COPY --from=builder /myapp/package.json ./package.json
    COPY --from=builder /myapp/public ./public
    CMD ["npm", "run", "start"]
