    # Stage 1: Build the Next.js application
    FROM node:18-alpine AS builder
    WORKDIR /app
    COPY package.json yarn.lock ./
    RUN yarn install --frozen-lockfile
    COPY . .
    RUN yarn build

    # Stage 2: Create the production image
    FROM node:18-alpine AS runner
    WORKDIR /app
    ENV NODE_ENV production
    COPY --from=builder /app/.next ./.next
    COPY --from=builder /app/node_modules ./node_modules
    COPY --from=builder /app/package.json ./package.json
    COPY --from=builder /app/public ./public
    CMD ["yarn", "start"]
