services:

  nextjs-app:
    container_name: nextjs-app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
      - .src:/app/src
