services:

  nextjs-app:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile-for-prod
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./public:/myapp/public
      - ./app:/myapp/app

  nginx_proxy:
    image: nginx 
    container_name: nginx_proxy 
    ports:
      - "80:80"  # <host port>:<container port>
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs-app 

